[[news]]
date = "2026-01"
content = "Our paper \"I2E: From Image Pixels to Actionable Interactive Environments for Text-Guided Image Editing\" appeared on arXiv and is currently under review for ACL 2026."

[[news]]
date = "2025-12"
content = "Received the First-class Academic Scholarship for the third consecutive year."

[[news]]
date = "2025-06"
content = "Won the National Second Prize in the 16th Lanqiao Cup National Software and IT Competition."

[[news]]
date = "2024-10"
content = "Won the National First Prize in Huawei's Spark Cup Mathematical Modeling Elite League."
