[[news]]
date = "2026-01"
content = "论文《I2E: From Image Pixels to Actionable Interactive Environments for Text-Guided Image Editing》发布于 arXiv，目前正在投稿 ACL 2026。"

[[news]]
date = "2025-12"
content = "连续第三年获得一等学业奖学金。"

[[news]]
date = "2025-06"
content = "获第十六届蓝桥杯全国软件和信息技术专业人才大赛全国二等奖。"

[[news]]
date = "2024-10"
content = "获华为“星火杯”数学建模精英联赛全国一等奖。"
